networks:
  auth-net:
    name: auth-net
    external: true
  socket-net:
    driver: bridge
    internal: true

volumes:
  auth-pgdata:
    name: auth-pgdata

services:
  socket-proxy:
    image: wollomatic/socket-proxy:1
    container_name: authentik-socket-proxy
    command:
      - "-loglevel=info"
      - "-allowfrom=authentik-worker"
      - "-listenip=0.0.0.0"
      - '-allowGET=^(/v[0-9\.]+)?/(version|info|containers/.*|events.*)$'
      - '-allowPOST=^(/v[0-9\.]+)?/(images/create|containers/create|containers/.*/(start|stop|kill))$'
      - '-allowDELETE=^(/v[0-9\.]+)?/containers/.*$'
      - "-shutdowngracetime=5"
      - "-watchdoginterval=600"
      - "-stoponwatchdog"
    restart: unless-stopped
    read_only: true
    mem_limit: 64M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    user: 65534:${DOCKER_GID}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket-net

  db:
    image: postgres:16-alpine
    container_name: authentik-db
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${AUTHENTIK_PG_DB} -U $${AUTHENTIK_PG_USER}",
        ]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    environment:
      POSTGRES_USER: ${AUTHENTIK_PG_USER}
      POSTGRES_DB: ${AUTHENTIK_PG_DB}
      POSTGRES_PASSWORD: ${AUTHENTIK_PG_PASSWORD}
    volumes:
      - auth-pgdata:/var/lib/postgresql/data
    networks:
      - auth-net

  server:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_VERSION_TAG}
    container_name: authentik-server
    command: server
    shm_size: 512mb
    restart: unless-stopped
    ports:
      - ${AUTHENTIK_PORT_HTTP}:9000
      - ${AUTHENTIK_PORT_HTTPS}:9443
    environment:
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_POSTGRESQL__HOST: db
      AUTHENTIK_POSTGRESQL__NAME: ${AUTHENTIK_PG_DB}
      AUTHENTIK_POSTGRESQL__USER: ${AUTHENTIK_PG_USER}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_PG_PASSWORD}
    volumes:
      - ./data:/data
      - ./templates:/templates
    depends_on:
      db:
        condition: service_healthy
    networks:
      - auth-net

  worker:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_VERSION_TAG}
    container_name: authentik-worker
    command: worker
    user: root
    shm_size: 512mb
    restart: unless-stopped
    environment:
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_POSTGRESQL__HOST: db
      AUTHENTIK_POSTGRESQL__NAME: ${AUTHENTIK_PG_DB}
      AUTHENTIK_POSTGRESQL__USER: ${AUTHENTIK_PG_USER}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_PG_PASSWORD}
      DOCKER_HOST: http://socket-proxy:2375
    volumes:
      - ./data:/data
      - ./certs:/certs
      - ./templates:/templates
    depends_on:
      db:
        condition: service_healthy
      socket-proxy:
        condition: service_started
    networks:
      - auth-net
      - socket-net
